language: php

php:
  - 5.3
  - 5.4
  - 5.5

services: mysql

before_script:
  - composer self-update
  - composer update --prefer-source --dev
  - mysql -e 'create database mysqltest;'
  - mysql --database=mysqltest < ./data/schema.sql
  - mkdir -p ./build/logs

script:
  - ./vendor/bin/phpunit -c phpunit.travis.xml --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR1 ./src/ ./tests/

after_script:
  - php vendor/bin/coveralls -v