language: php

php:
  - 5.3
  - 5.4
  - 5.5

services: mysql

before_script:
  - composer self-update
  - composer update --prefer-source --dev
  - mysql -e 'create database mysqltest;'

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

after_script:
  - php vendor/bin/coveralls -v